camera:
  fx: 1266.417203
  fy: 1266.417203
  cx: 816.2670196
  cy: 491.5075969
  height: 1.51

grid:
  size: 40.0
  resolution: 0.1
  height_thresh: 0.5

models:
  yolo: yolov8n.pt
  depth: MiDaS_small

nuscenes:
  dataroot: "data/nuscenes"      # relative path — works on any machine
  version: "v1.0-mini"

depth:
  scale_factor: 20.0
  min_depth: 1.0
  max_depth: 50.0